-- Run this in Supabase Dashboard > SQL Editor.
-- Supabase Auth stores credentials in auth.users. This table stores only
-- user-facing profile information and links each row to its Auth account.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null default '',
  phone_number text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Also adds the field when profiles was created using the earlier SQL version.
alter table public.profiles
  add column if not exists phone_number text not null default '';

alter table public.profiles enable row level security;

grant select, update on public.profiles to authenticated;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, phone_number)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone_number', '')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Rental equipment shown on menu.html. Existing rental rows are preserved.
create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  name text not null,
  total integer not null default 0,
  available integer not null default 0,
  price numeric(10, 2) not null default 0
);

alter table public.inventory
  add column if not exists id bigint generated by default as identity,
  add column if not exists name text not null default '',
  add column if not exists total integer not null default 0,
  add column if not exists available integer not null default 0,
  add column if not exists price numeric(10, 2) not null default 0,
  add column if not exists description text not null default '',
  add column if not exists image_path text not null default '',
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.inventory'::regclass and contype = 'p'
  ) then
    alter table public.inventory add constraint inventory_pkey primary key (id);
  end if;
end;
$$;

-- Cleaning items sold through store.html use a separate table from rentals.
create table if not exists public.cleaning_products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  price numeric(10, 2) not null default 0 check (price >= 0),
  total integer not null default 0 check (total >= 0),
  available integer not null default 0 check (available >= 0 and available <= total),
  image_path text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  legacy_inventory_id bigint unique
);

alter table public.cleaning_products
  add column if not exists legacy_inventory_id bigint;

create unique index if not exists cleaning_products_legacy_inventory_id_key
  on public.cleaning_products (legacy_inventory_id);

-- Earlier versions saved cleaning products in inventory. Retail-priced rows
-- are copied to the cleaning catalog and hidden from the public rental list.
insert into public.cleaning_products (
  name, description, price, total, available, image_path, is_active, legacy_inventory_id
)
select name, description, price, total, available, image_path, is_active, id
from public.inventory
where price > 0
on conflict (legacy_inventory_id) do nothing;

update public.inventory as rental_item
set is_active = false
where rental_item.price > 0
  and exists (
    select 1 from public.cleaning_products as cleaning_item
    where cleaning_item.legacy_inventory_id = rental_item.id
  );

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade
);

alter table public.admin_users enable row level security;
revoke all on public.admin_users from anon, authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

alter table public.inventory enable row level security;
revoke all on public.inventory from anon, authenticated;
grant select on public.inventory to anon, authenticated;
grant insert, update, delete on public.inventory to authenticated;

drop policy if exists "Anyone can view active store items" on public.inventory;
drop policy if exists "Anyone can view active rental items" on public.inventory;
create policy "Anyone can view active rental items"
  on public.inventory for select to anon, authenticated
  using (is_active);

drop policy if exists "Admins can manage store items" on public.inventory;
drop policy if exists "Admins can manage rental items" on public.inventory;
create policy "Admins can manage rental items"
  on public.inventory for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Only admins can insert store items" on public.inventory;
drop policy if exists "Only admins can insert rental items" on public.inventory;
create policy "Only admins can insert rental items"
  on public.inventory as restrictive for insert to authenticated
  with check (public.is_admin());

drop policy if exists "Only admins can update store items" on public.inventory;
drop policy if exists "Only admins can update rental items" on public.inventory;
create policy "Only admins can update rental items"
  on public.inventory as restrictive for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Only admins can delete store items" on public.inventory;
drop policy if exists "Only admins can delete rental items" on public.inventory;
create policy "Only admins can delete rental items"
  on public.inventory as restrictive for delete to authenticated
  using (public.is_admin());

alter table public.cleaning_products enable row level security;
revoke all on public.cleaning_products from anon, authenticated;
grant select on public.cleaning_products to anon, authenticated;
grant insert, update, delete on public.cleaning_products to authenticated;

drop policy if exists "Anyone can view active cleaning products" on public.cleaning_products;
create policy "Anyone can view active cleaning products"
  on public.cleaning_products for select to anon, authenticated
  using (is_active);

drop policy if exists "Admins can manage cleaning products" on public.cleaning_products;
create policy "Admins can manage cleaning products"
  on public.cleaning_products for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Only admins can insert cleaning products" on public.cleaning_products;
create policy "Only admins can insert cleaning products"
  on public.cleaning_products as restrictive for insert to authenticated
  with check (public.is_admin());

drop policy if exists "Only admins can update cleaning products" on public.cleaning_products;
create policy "Only admins can update cleaning products"
  on public.cleaning_products as restrictive for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Only admins can delete cleaning products" on public.cleaning_products;
create policy "Only admins can delete cleaning products"
  on public.cleaning_products as restrictive for delete to authenticated
  using (public.is_admin());

insert into storage.buckets (id, name, public)
values ('store-products', 'store-products', true)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('rental-items', 'rental-items', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Admins can upload store product images" on storage.objects;
create policy "Admins can upload store product images"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'store-products' and public.is_admin());

drop policy if exists "Admins can update store product images" on storage.objects;
create policy "Admins can update store product images"
  on storage.objects for update to authenticated
  using (bucket_id = 'store-products' and public.is_admin())
  with check (bucket_id = 'store-products' and public.is_admin());

drop policy if exists "Admins can delete store product images" on storage.objects;
create policy "Admins can delete store product images"
  on storage.objects for delete to authenticated
  using (bucket_id = 'store-products' and public.is_admin());

drop policy if exists "Admins can upload rental item images" on storage.objects;
create policy "Admins can upload rental item images"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'rental-items' and public.is_admin());

drop policy if exists "Admins can update rental item images" on storage.objects;
create policy "Admins can update rental item images"
  on storage.objects for update to authenticated
  using (bucket_id = 'rental-items' and public.is_admin())
  with check (bucket_id = 'rental-items' and public.is_admin());

drop policy if exists "Admins can delete rental item images" on storage.objects;
create policy "Admins can delete rental item images"
  on storage.objects for delete to authenticated
  using (bucket_id = 'rental-items' and public.is_admin());

-- After creating your account, grant it admin access with its auth.users UUID:
-- insert into public.admin_users (user_id) values ('YOUR_AUTH_USER_UUID');
